// <auto-generated />
using System;
using Git_Watcher.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Git_Watcher.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190627193134_GitRepoModelChanged")]
    partial class GitRepoModelChanged
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Git_Watcher.Models.GitRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Link")
                        .IsRequired();

                    b.Property<string>("RepoId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("GitRepos","dbo");
                });

            modelBuilder.Entity("Git_Watcher.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("RepoId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions","dbo");
                });

            modelBuilder.Entity("Git_Watcher.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ApiKey");

                    b.Property<string>("GitUserName")
                        .IsRequired()
                        .HasMaxLength(39);

                    b.HasKey("Id");

                    b.ToTable("Users","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
